appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: EsGcqbGVneUIANyAxJ9Cs+E3xjKfCo9lJwOQRrDovLKq1+Sy9/ksYd/xLtpSrpub3+s6wKSlaqkYDptWflA8jqcxJiuN4ohCbC0K9B37x1p0dyA7ttwEa8BlH7ohouSA2KykNilLu04LZ3wsEOgtrAev2FJ+a3pfk/9PzOyw6zGP8DJjh8q5jGDmvQSEeyPngPDmz8J+E1m31XZvHdvIO13iDo74DJNWK4+TGG2MvF/kGGpsPMCuwtB+ARIQDWpgAS+0AgPatVVYbnCWV0D/NEh8P5RjTxGKrJIKYSa8cLsPPAGsZ4MCSdC+DJzZ/mh63VYzlQ7mXPYBLPYHh2/Hx5x8pa3QAFPBdg9miTTITUOdzaqhj9lZrD7WMO228JIHrJ9NqyiYxLh3QIsPxQj/XQQgixI0wmQsbg3owbFDEUi9n7Q2d/WoBlxa1YMOQzazI7x2esttgqflXdXlBN/nUFdtCtAuO+tAnu96tuApDgez3+25GT1wMoQdvt4ydaUWUK11bAVi47RjPurlW2YholY6FIqYT08yl94oxHBHie45QEWkgdQUZVYYLVS4EZXH+0cCxzODGb36GsQsg40n3uJ7PmNTIb0NFfHWYGvcPWvTq8wSpF2j8L2lVIjEK6MIqa8jczh1EvlfN5t0JONPE80bEaEkC+rJUVAzz2MHfUA=
conda_forge_output_validation: true
